#Project Info
site_name: Enrique Calderon-Sastre / Sofware Engineer
site_url: https://ecaldrn.github.io/
site_author: Enrique Calderon-Sastre
site_description: >-
  I'm Enrique Calderon-Sastre, a SWE interested in automotive software, 
  computer vision and general software engineering (mostly C++ and Python)

# Settings
repo_name: ecaldrn/ecaldrn.github.io
# repo_url: https://github.com/ecaldrn/ecaldrn.github.io

# Plugins
plugins:
  - search
  - blog:
      blog_dir: blog
      blog_toc: true
      
theme:
  name: material
  custom_dir: overrides/
  language: en
  icon:
    logo: fontawesome/regular/keyboard
    favicon: fontawesome/regular/keyboard
  font:
    text: Roboto
  features:
    - content.code.annotate

  # Page color settings  
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
      primary: teal
      accent: blue
    # Dark mode 
    - scheme: slate 
      toggle:
        icon: material/brightness-7
        name: Switch to light mode    
      primary: teal
      accent: blue

  # Page features
  features:
    search.suggest
    - search.highlight
    content.code.annotation
    content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.tooltips
    - content.code.annotation
    - content.code.copy

# Page tree: refer to mkdocs documentation
nav:
- Home: index.md
- Projects:
  - ./Projects/Project1.md
  - ./Projects/Project2.md
  - ./Projects/Project3.md
  
- Notes:
  - Automotive SW:
    - ./Notes/automotive/canbus.md
  - C++:
    - ./Notes/cpp/cpp.md
  - Computer Science Topics:
    - ./Notes/cs/linux.md
  - Data Structures and Algorithms:
    - ./Notes/dsa/ds.md
    - ./Notes/dsa/algorithms.md
  - Python:
    - ./Notes/python/python.md

- Blog:
  - blog/index.md

# Links to social media
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ecaldrn
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/enriquecalderonsastre/
    #- icon: octicons/mail-16
      #link: ecalderon_1@hotmail.com
      #<a href="mailto:ecalderon_1@hotmail.com">

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  &copy; <script type="text/javascript">document. write(new Date(). getFullYear() );</script> <a href="https://github.com/ecaldrn"  target="_blank" rel="noopener">Enrique Calderon-Sastre</a>