#Project Info
site_name: Enrique Calderon-Sastre / Sofware Engineer
site_url: https://ecaldrn.github.io/
site_author: Enrique Calderon-Sastre
site_description: >-
  I'm Enrique Calderon-Sastre, a SWE interested in automotive software, 
  computer vision and general software engineering (mostly C++ and Python)

# Settings
repo_name: ecaldrn/ecaldrn.github.io
repo_url: https://github.com/ecaldrn/ecaldrn.github.io
theme:
  name: material
  language: en
  icon:
    logo: fontawesome/regular/keyboard
    favicon: 
  font:
    text: Roboto

  # Page color settings  
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
      primary: teal
      accent: purple
    # Dark mode 
    - scheme: slate 
      toggle:
        icon: material/brightness-7
        name: Switch to light mode    
      primary: teal
      accent: blue
      
  # Page features
  features:
    search.suggest
    content.code.annotation
    content.code.copy

# Page tree: refer to mkdocs documentation
nav:
- Home: index.md
- Portfolio:
  - Project1.md
  - Project2.md
  - Project3.md

# Links to social media
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ecaldrn
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/enriquecalderonsastre/
    #- icon: octicons/mail-16
      #link: ecalderon_1@hotmail.com
      #<a href="mailto:ecalderon_1@hotmail.com">

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; <script type="text/javascript">document. write(new Date(). getFullYear() );</script> <a href="https://github.com/ecaldrn"  target="_blank" rel="noopener">Enrique Calderon-Sastre</a>