#Project Info
site_name: Enrique Calderon-Sastre
site_url: https://ecaldrn.github.io/
site_author: Enrique Calderon-Sastre
site_description: >-
  I'm Enrique Calderon-Sastre, a SWE interested in automotive software, 
  computer vision and general software engineering (mostly C++ and Python)

# Settings
repo_name: ecaldrn/ecaldrn.github.io
repo_url: https://github.com/ecaldrn/ecaldrn.github.io
theme:
  name: material

# Page tree: refer to mkdocs documentation
nav:
- Home: index.md
- Portfolio:
  - Project1.md
  - Project2.md
  - Project3.md