authors:
  ecaldrn:
    name: Enrique CS
    description: Creator
    avatar: https://media.licdn.com/dms/image/v2/D5603AQF0f6imWL_MZA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1719557555336?e=1729123200&v=beta&t=K8ufKI4L6NNB4KqW1g7p_wuOpoaWvdAnUWSj9KRxZAY